# Generated by Django 6.0.3 on 2026-04-20 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matrix_a', models.JSONField()),
                ('matrix_b', models.JSONField(blank=True, null=True)),
                ('operation', models.CharField(max_length=50)),
                ('result', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История вычислений',
                'verbose_name_plural': 'История вычислений',
                'ordering': ['-created_at'],
            },
        ),
    ]
