# Generated by Django 6.0.3 on 2026-04-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={'ordering': ['created_at'], 'verbose_name': 'Пример', 'verbose_name_plural': 'Примеры'},
        ),
    ]
